# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sph_filt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sphere_filtration(object):
    def setupUi(self, sphere_filtration):
        sphere_filtration.setObjectName("sphere_filtration")
        sphere_filtration.setEnabled(True)
        sphere_filtration.resize(999, 474)
        sphere_filtration.setStyleSheet("\n"
"QPushButton{\n"
"background-color: grey;\n"
"width:100px;\n"
"length:200px;\n"
"font-size: 14px;\n"
"font-weight:bold;\n"
"border:none;\n"
"text-align:center;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:silver;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgb(96, 255, 39);\n"
"}\n"
"QLabel{\n"
"\n"
"width:100px;\n"
"length:200px;\n"
"font-size: 14px;\n"
"font-weight:bold;\n"
"border:none;\n"
"text-align:center;\n"
"}\n"
"\n"
"QTextEdit{\n"
"width:100px;\n"
"length:200px;\n"
"font-size: 14px;\n"
"}\n"
"")
        self.label = QtWidgets.QLabel(sphere_filtration)
        self.label.setGeometry(QtCore.QRect(20, 70, 711, 391))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("spheres.png"))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(sphere_filtration)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(760, 70, 226, 178))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(sphere_filtration)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(760, 260, 231, 159))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.label_3 = QtWidgets.QLabel(sphere_filtration)
        self.label_3.setGeometry(QtCore.QRect(100, 20, 831, 31))
        self.label_3.setStyleSheet("background-color: rgb(121, 255, 239)")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(sphere_filtration)
        QtCore.QMetaObject.connectSlotsByName(sphere_filtration)

    def retranslateUi(self, sphere_filtration):
        _translate = QtCore.QCoreApplication.translate
        sphere_filtration.setWindowTitle(_translate("sphere_filtration", "Form"))
        self.label_2.setText(_translate("sphere_filtration", "Введите название .xlsx файла:"))
        self.pushButton.setText(_translate("sphere_filtration", "Импортировать"))
        self.pushButton_2.setText(_translate("sphere_filtration", "ВЫПОЛНИТЬ РАСЧЕТ "))
        self.pushButton_3.setText(_translate("sphere_filtration", "Экспортировать"))
        self.label_3.setText(_translate("sphere_filtration", "Моделирование движения жидкости к скважинам различной конфигурации при помощи сферического потока"))
